root: true

parser: babel-eslint

extends: [eslint:recommended, plugin:import/errors, plugin:import/warnings]
plugins: [import]

settings:
  import/resolver:
    node:
      moduleDirectory: ["node_modules", "src/"]

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true
  jasmine: true
  node: true

globals:
  MockFirebase: true
  sinon: true

rules:
  camelcase: 2
  comma-spacing: 2
  comma-dangle: [2, always-multiline]
  consistent-return: 2
  dot-notation: [2, {allowKeywords: true, allowPattern: "^[a-z]+(_[a-z]+)+$"}]
  eol-last: 2
  eqeqeq: 2
  jsx-quotes: 1
  new-cap: 0
  new-parens: 2
  no-alert: 2
  no-caller: 2
  no-catch-shadow: 2
  no-class-assign: 2
  no-const-assign: 2
  no-eval: 2
  no-extra-bind: 2
  no-extend-native: 2
  no-implied-eval: 2
  no-invalid-this: 0
  no-lone-blocks: 2
  no-lonely-if: 2
  no-multi-str: 2
  no-native-reassign: 2
  no-new-func: 2
  no-new-object: 2
  no-shadow: 0
  no-shadow-restricted-names: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unused-expressions: [2, {allowShortCircuit: true, allowTernary: true }]
  no-with: 2
  no-unused-vars: 0
  quotes: [1, "single", { avoidEscape: true }]
  semi: 2
  semi-spacing: [2, {before: false, after: true}]
  space-infix-ops: 2
  keyword-spacing: 2
  space-unary-ops: [2, {words: true, nonwords: false}]
  wrap-iife: 2
  yoda: [2, never]
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 0
  import/namespace: 2
  import/default: 0
  import/export: 2
  import/no-named-as-default: 0